"""add vector id to document chunks

Revision ID: 716a3cf2c68b
Revises: f2529669f049
Create Date: 2026-07-15 13:31:02.572127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716a3cf2c68b'
down_revision: Union[str, Sequence[str], None] = 'f2529669f049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('vector_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'vector_id')
    # ### end Alembic commands ###
