from datetime import timedelta

ACCESS_TOKEN_EXPIRE_MINUTES = 60
ALGORITHM = "HS256"

SECRET_KEY = "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_FOR_DEVELOPMENT"

ACCESS_TOKEN_EXPIRE = timedelta(
    minutes=ACCESS_TOKEN_EXPIRE_MINUTES
)